### ISSUE TITLE
work on FF 39 ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud-archive/mozilla_sync#141]
There are some controversial issues, and there is no overview on which FF it is working. 
So before I start to use: 
Please can someone confirm, that mozilla_sync is working on FF39 ?
Or please can someone, who knows , update README.md with confirmed running FF ?

Thank you

**Comment by quenenni** [comment]
Well, it worked perfectly for me with IceWeasel 39.0a2 (2015-04-06) and owncloud 8.02.

**Comment by quenenni** [comment]
Hooo.. nice..

I took mozilla_sync from this repository instead of the one from the owncloud app site and it's working.. That's very very nice.

A big thanks to the devs for the hard (and efficient) work.

PS: the changelog file should be updated. It's the same from the owncloud app site and you definitely did work on it since 02/2014.
